config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  get '/index', to: 'application#index', as: :index
  get '/scene', to: 'application#scene', as: :render_scene
  get '/event_part', to: 'application#event_part', as: :render_event_part

  scope module: :admin do
    get '/admin', to: 'scenes#index'
    resources :scenes
    resources :events
    resources :event_parts
    resources :event_answers
    resources :scene_connectors
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :scene
  has_many :event_parts
  has_many :event_answers, through: :event_parts

  validates :name, presence: true

  delegate :name, to: :scene, prefix: true

  def start_event_part
    event_parts.first
  end
end

app/models/events/event_answers_display.rb
module Events
  class EventAnswersDisplay
    include ActionView::Helpers::TagHelper
    include ActionView::Context

    FIRST_ANSWER_POSITION_Y = 200
    ANSWER_GAP = 20

    attr_reader :event_answers

    def initialize(event_answers)
      @event_answers = event_answers
    end

    def call
      event_answers.present? ? event_answer_box : ''
    end

    private

      def event_answer_box
        content_tag(:div, class: :event_answer_box) do
          position_y = FIRST_ANSWER_POSITION_Y
          event_answers.collect do |event_answer|
            link = event_answer_link(event_answer, position_y)
            position_y += ANSWER_GAP
            link
          end.join.html_safe
        end.html_safe
      end

      def event_answer_link(event_answer, position_y)
        event_answer.to_link(link_html_options) do
          content_tag(:div, class: [:bordered_box_black], style: "top: #{position_y}px; position: relative;") do
            event_answer.answer
          end
        end
      end

      def link_html_options
        {
          class: :event_answer_link,
          remote: true
        }
      end
  end
end

app/models/events/event_checker.rb
module Events
  class EventChecker
    MAX_POSSIBILTY = 100
    MIN_POSSIBILTY = 0

    attr_reader :events

    def initialize(scene)
      @events = scene.events.where(active: true)
    end

    # Returns nil of no event was triggered or the scene has no events
    def call
      catch_event unless no_event_possible?
    end

    private

      def catch_event
        enfored_event? ? enfore_most_possible_event : catch_random_event
      end

      def enfore_most_possible_event
        events.max_by(&:possibility)
      end

      def catch_random_event
        EventDistribution.new(events).pick_random
      end

      def sum_of_possibilities
        @sum_of_possibilities ||= events.reduce(0) { |sum, event| sum + event.possibility }
      end

      def no_event_possible?
        sum_of_possibilities == MIN_POSSIBILTY
      end

      def enfored_event?
        sum_of_possibilities >= MAX_POSSIBILTY
      end

  end
end

app/models/events/event_distribution.rb
module Events
  class EventDistribution
    DISTRIBUTION_MIN = 1
    DISTRIBUTION_MAX = 100

    attr_reader :event_distribution

    def initialize(events)
      build_event_distribution(events)
    end

    def pick_random
      pick_random_from_number(rand(DISTRIBUTION_MIN..DISTRIBUTION_MAX)) unless event_distribution.present?
    end

    private

      def pick_random_from_number(number)
        event_distribution.detect { |key, value| key.includes?(number) }
      end

      def build_event_distribution(events)
        max = DISTRIBUTION_MIN
        events.each do |event|
          possibility = event.possibility
          event_distribution[(max..possibility)] = event
          max = possibility
        end
        event_distribution[(max..DISTRIBUTION_MAX)] = nil
      end
  end
end

app/models/events/event_text_display.rb
module Events
  class EventTextDisplay
    include ActionView::Helpers::TagHelper
    include ActionView::Context

    attr_reader :event

    def initialize(event)
      @event = event
    end

    def call
      content_tag(:div, class: [:event_part_text_box, :bordered_box_black]) do
        content_tag(:h2, event.title, class: :text_box_title) +
        content_tag(:div, event.text, class: :text_box_text_area)
      end
    end
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < AdminController
    before_action :set_event, only: [:show, :edit, :update, :destroy]
    before_action :load_scenes, only: [:edit, :new]

    # GET /events
    # GET /events.json
    def index
      @events = Event.includes(:scene).all
    end

    # GET /events/1
    # GET /events/1.json
    def show
    end

    # GET /events/new
    def new
      @event = Event.new
    end

    # GET /events/1/edit
    def edit
    end

    # POST /events
    # POST /events.json
    def create
      @event = Event.new(event_params)

      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /events/1
    # PATCH/PUT /events/1.json
    def update
      respond_to do |format|
        if @event.update(event_params)
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_event
        @event = Event.find(params[:id])
      end

      def load_scenes
        @scenes = Scene.all
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def event_params
        params.require(:event).permit(:name, :active, :possibility, :scene_id)
      end
  end
end

app/helpers/event_helper.rb
module EventHelper

  def link_to_event(name, id)
    link_to(event_path(id)) do
      "#{name}(Id: #{id})"
    end
  end

end

app/views/admin/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :possibility %>
    <%= f.number_field :possibility, within: 1...101 %>
  </div>
  <div class="field">
    <%= f.label :scene %>
    <%= f.select :scene_id, options_for_select(@scenes.map{ |s| [s.name, s.id] }) %>
  </div>

  <div class="actions">
    <%= link_to_function('Back', 'history.back()', class: :form_back_link) %> |
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

app/views/admin/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Active</th>
      <th>Possibility</th>
      <th>Scene</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.name %></td>
        <td><%= event.active %></td>
        <td><%= event.possibility %></td>
        <td><%= link_to_scene(event.scene_name, event.scene_id) %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/admin/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

app/views/admin/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>