config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  get '/index', to: 'application#index', as: :index
  get '/scene', to: 'application#scene', as: :render_scene
  get '/event_part', to: 'application#event_part', as: :render_event_part

  scope module: :admin do
    get '/admin', to: 'scenes#index'
    resources :scenes
    resources :events
    resources :event_parts
    resources :event_answers
    resources :scene_connectors
  end

end

app/models/event_part.rb
class EventPart < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Context

  belongs_to :event
  has_many :event_answers

  has_attached_file :image, styles: {thumb: "100x100>"}, default_url: "/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :name, :title, :text, :next_type, :next_id, presence: true

  delegate :name, to: :event, prefix: true

  def to_view
    event_answers.exists? ? to_view_with_answers : to_view_without_answers
  end

  private

    def to_view_with_answers
      event_part_main_scene_tag do
        Events::EventAnswersDisplay.new(event_answers).call.html_safe +
        Events::EventTextDisplay.new(self).call.html_safe
      end
    end

    def to_view_without_answers
      link_to(send("render_#{next_type}_path", "#{next_type}_id": next_id), remote: true) do
        event_part_main_scene_tag do
          content_tag(:div, nil, class: :event_answer_box).html_safe +
          Events::EventTextDisplay.new(self).call.html_safe
        end
      end.html_safe
    end

    def event_part_main_scene_tag
      content_tag(:div, id: 'main_scene', style:"background-image: url(#{image.url});") do
        yield
      end.html_safe
    end

end

app/controllers/admin/event_parts_controller.rb
module Admin
  class EventPartsController < AdminController
    before_action :set_event_part, only: [:show, :edit, :update, :destroy]
    before_action :load_events, only: [:edit, :new, :create]

    # GET /event_parts
    # GET /event_parts.json
    def index
      @event_parts = EventPart.includes(:event).all
    end

    # GET /event_parts/1
    # GET /event_parts/1.json
    def show
    end

    # GET /event_parts/new
    def new
      @event_part = EventPart.new
    end

    # GET /event_parts/1/edit
    def edit
    end

    # POST /event_parts
    # POST /event_parts.json
    def create
      @event_part = EventPart.new(event_part_params)

      respond_to do |format|
        if @event_part.save
          format.html { redirect_to @event_part, notice: 'Event part was successfully created.' }
          format.json { render :show, status: :created, location: @event_part }
        else
          format.html { render :new }
          format.json { render json: @event_part.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /event_parts/1
    # PATCH/PUT /event_parts/1.json
    def update
      respond_to do |format|
        if @event_part.update(event_part_params)
          format.html { redirect_to @event_part, notice: 'Event part was successfully updated.' }
          format.json { render :show, status: :ok, location: @event_part }
        else
          format.html { render :edit }
          format.json { render json: @event_part.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /event_parts/1
    # DELETE /event_parts/1.json
    def destroy
      @event_part.destroy
      respond_to do |format|
        format.html { redirect_to event_parts_url, notice: 'Event part was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_event_part
        @event_part = EventPart.find(params[:id])
      end

      def load_events
        @events = Event.all
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def event_part_params
        params.require(:event_part).permit(:name, :title, :text, :next_type, :next_id, :image, :event_id)
      end
  end
end

app/helpers/event_part_helper.rb
module EventPartHelper

  def link_to_event_part(name, id)
    link_to(event_path(id)) do
      "#{name}(Id: #{id})"
    end
  end

end

app/views/admin/event_parts/_form.html.erb
<%= form_for(@event_part) do |f| %>
  <% if @event_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_part.errors.count, "error") %> prohibited this event_part from being saved:</h2>

      <ul>
      <% @event_part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :next_type %>
    <%= f.text_field :next_type %>
  </div>
  <div class="field">
    <%= f.label :next_id %>
    <%= f.text_field :next_id %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :event_id %>
    <%= f.select :event_id, options_for_select(@events.map{ |s| [s.name, s.id] }) %>
  </div>

  <div class="actions">
    <%= link_to_function('Back', 'history.back()', class: :form_back_link) %> |
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/event_parts/edit.html.erb
<h1>Editing Event Part</h1>

<%= render 'form' %>

app/views/admin/event_parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Event Parts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Title</th>
      <th>Text</th>
      <th>Next Is Of Type</th>
      <th>Next Id</th>
      <th>Image</th>
      <th>Event Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_parts.each do |event_part| %>
      <tr>
        <td><%= event_part.id %></td>
        <td><%= event_part.name %></td>
        <td><%= event_part.title %></td>
        <td><%= event_part.text %></td>
        <td><%= event_part.next_type %></td>
        <td><%= event_part.next_id %></td>
        <td><%= image_tag event_part.image.url(:thumb) %></td>
        <td><%= link_to_event(event_part.event_name, event_part.event_id) %></td>
        <td><%= link_to 'Show', event_part %></td>
        <td><%= link_to 'Edit', edit_event_part_path(event_part) %></td>
        <td><%= link_to 'Destroy', event_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event part', new_event_part_path %>

app/views/admin/event_parts/new.html.erb
<h1>New Event Part</h1>

<%= render 'form' %>

app/views/admin/event_parts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_part_path(@event_part) %> |
<%= link_to 'Back', event_parts_path %>