config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  get '/index', to: 'application#index', as: :index
  get '/scene', to: 'application#scene', as: :render_scene
  get '/event_part', to: 'application#event_part', as: :render_event_part

  scope module: :admin do
    get '/admin', to: 'scenes#index'
    resources :scenes
    resources :events
    resources :event_parts
    resources :event_answers
    resources :scene_connectors
  end

end

app/models/event_answer.rb
class EventAnswer < ActiveRecord::Base
  include ActionView::Context
  include Rails.application.routes.url_helpers
  include ActionView::Helpers::UrlHelper

  belongs_to :event_part

  validates :name, :answer, :next_type, :next_id, presence: true

  def to_link(html_options = {})
    link_to(send("render_#{next_type}_path", "#{next_type}_id": next_id), html_options) do
      yield
    end.html_safe
  end
end

app/controllers/admin/event_answers_controller.rb
module Admin
  class EventAnswersController < AdminController
    before_action :set_event_answer, only: [:show, :edit, :update, :destroy]
    before_action :load_event_parts, only: [:edit, :new]

    # GET /event_answers
    # GET /event_answers.json
    def index
      @event_answers = EventAnswer.all
    end

    # GET /event_answers/1
    # GET /event_answers/1.json
    def show
    end

    # GET /event_answers/new
    def new
      @event_answer = EventAnswer.new
    end

    # GET /event_answers/1/edit
    def edit
    end

    # POST /event_answers
    # POST /event_answers.json
    def create
      @event_answer = EventAnswer.new(event_answer_params)

      respond_to do |format|
        if @event_answer.save
          format.html { redirect_to @event_answer, notice: 'Event answer was successfully created.' }
          format.json { render :show, status: :created, location: @event_answer }
        else
          format.html { render :new }
          format.json { render json: @event_answer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /event_answers/1
    # PATCH/PUT /event_answers/1.json
    def update
      respond_to do |format|
        if @event_answer.update(event_answer_params)
          format.html { redirect_to @event_answer, notice: 'Event answer was successfully updated.' }
          format.json { render :show, status: :ok, location: @event_answer }
        else
          format.html { render :edit }
          format.json { render json: @event_answer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /event_answers/1
    # DELETE /event_answers/1.json
    def destroy
      @event_answer.destroy
      respond_to do |format|
        format.html { redirect_to event_answers_url, notice: 'Event answer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_event_answer
        @event_answer = EventAnswer.find(params[:id])
      end

      def load_event_parts
        @event_parts = EventPart.all
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def event_answer_params
        params.require(:event_answer).permit(:name, :answer, :next_type, :next_id, :event_part_id)
      end
  end
end

app/views/admin/event_answers/_form.html.erb
<%= form_for(@event_answer) do |f| %>
  <% if @event_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_answer.errors.count, "errors") %> prohibited this event_answer from being saved:</h2>

      <ul>
      <% @event_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :answer %>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :next_type %>
    <%= f.text_field :next_type %>
  </div>
  <div class="field">
    <%= f.label :next_id %>
    <%= f.number_field :next_id %>
  </div>
  <div class="field">
    <%= f.label :event_part_id %>
    <%= f.select :event_part_id, options_for_select(@event_parts.map{ |s| [s.name, s.id] }) %>
  </div>

  <div class="actions">
    <%= link_to_function('Back', 'history.back()', class: :form_back_link) %> |
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/event_answers/edit.html.erb
<h1>Editing Event Answer</h1>

<%= render 'form' %>

app/views/admin/event_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Event Answers</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Answer</th>
      <th>Next type</th>
      <th>Next</th>
      <th>EventPartId</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_answers.each do |event_answer| %>
      <tr>
        <td><%= event_answer.id %></td>
        <td><%= event_answer.name %></td>
        <td><%= event_answer.answer %></td>
        <td><%= event_answer.next_type %></td>
        <td><%= event_answer.next_id %></td>
        <td><%= event_answer.event_part_id %></td>
        <td><%= link_to 'Show', event_answer %></td>
        <td><%= link_to 'Edit', edit_event_answer_path(event_answer) %></td>
        <td><%= link_to 'Destroy', event_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event answer', new_event_answer_path %>

app/views/admin/event_answers/new.html.erb
<h1>New Event Answer</h1>

<%= render 'form' %>

app/views/admin/event_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer:</strong>
  <%= @event_answer.answer %>
</p>

<p>
  <strong>Next type:</strong>
  <%= @event_answer.next_type %>
</p>

<p>
  <strong>Next:</strong>
  <%= @event_answer.next_id %>
</p>

<%= link_to 'Edit', edit_event_answer_path(@event_answer) %> |
<%= link_to 'Back', event_answers_path %>